package com.example.accessingdatamysql;


import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


import org.springframework.ui.Model;

import org.springframework.web.bind.annotation.PathVariable;

@RestController	// This means that this class is a Controller
@RequestMapping(path="/user-rest")
public class UserControllerRest {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	

	@GetMapping("/add")
	public String userForm(User user) {
		return "form";
	}
	
	@PostMapping(path="/add") // Map ONLY POST Requests
	public String addNewUser (@RequestBody User user) {
		
		userRepository.save(user);

		return user.toString();
	}
	
	@GetMapping(path="/all")
	public  Iterable<User>getAllUsers(Model model) {//在数据库内获取所有数据
		// This returns a JSON or XML with the PersonForms
		Iterable<User> userList = userRepository.findAll();
		return userList;
		
	}
	@DeleteMapping(path="/delete/{id}")
	public void deleteUserById(@PathVariable("id") int id){
		userRepository.deleteById(id);
	}
	
}
